name: Auto crawl

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python3 --version
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: init
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          cd rec_probing
          pip install -e .
      - name: download_make dir
        run: |
          cd data
          mkdir search
          mkdir dialogue
          cd search
      - name: download_data_script
        run: |
          wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1quaTeELrdydQ9uFJi_EfruuoNPJ0TnhF' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1quaTeELrdydQ9uFJi_EfruuoNPJ0TnhF" -O imdb_reviews.csv.zip && rm -rf /tmp/cookies.txt
          unzip imdb_reviews.csv.zip
          rm imdb_reviews.csv.zip
          wget "http://files.grouplens.org/datasets/movielens/ml-25m.zip"
          unzip ml-25m.zip
          mv ml-25m/* ./
          mv movies.csv movies_names.csv
          mv ratings.csv ml25m_ratings.csv
          wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1naj_8j0MeCH2ZZ8u8WKLJqKDEoc5kggN' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1naj_8j0MeCH2ZZ8u8WKLJqKDEoc5kggN" -O dialogues.csv.zip && rm -rf /tmp/cookies.txt
          unzip dialogues.csv.zip
          git clone https://github.com/ReDialData/website.git
          git checkout data
      - name: dataset creation
        run: |
          cd data/
          cd recommendation
          mkdir gr
          cd ../
          cd../
          mkdir ml25m
          cd../
          cd ../
          cd search
          mkdir gr
          mkdir ml25m
          cd ../
          cd ../
          cd dialogue
          mkdir books
          mkdir movies
          cd data/
          sbatch create_dialogue_datasets.sbatch
          sbatch create_recommendation_datasets.sbatch
          sbatch create_search_datasets.sbatch
      - name: run
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          cd rec_probing
          pip install -e .
          python3 rec_probing/scripts/run_probes.py \
          --task  gr \
          --probe_type recommendation \
          --input_folder $REPO_DIR/data/recommendation \
          --output_folder $REPO_DIR/data/output_data/probes/ \
          --number_queries 4 \
          --number_candidates 5 \
          --batch_size 64 \
          --probe_technique nsp \
          --bert_model 'bert-base-cased'
      # - name: Build Web App with canvaskit renderer
      #   run: |
      #     flutter build web --web-renderer canvaskit
      #     cd build/web
      #     zip -r web-app-canvaskit.zip .
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ""
      # - name: download
      #   run: |
      #     ./download_data.sh
      #     ./run_datasets_creation.sh
